### ISSUE TITLE
webp 1.3.1 causes build fail (with fix)

### ISSUE THREAD

**Issue by gene-git** [Motion-Project/motionplus#74]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x (git HEAD)

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Other

### Disto version number

Arch linux Fully updated

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

AFter updating webp to 1.3.1 compiling fails with:

 `/usr/bin/ld: picture.o: undefined reference to symbol 'WebPMemoryWriterInit'`

Fix requires adding libwebp in addition to libwebpmux.

The following patch to configure.ac fixes it for me:

```
diff -u a/configure.ac b/configure.ac
--- a/configure.ac	2023-06-30 10:03:14.179112133 -0400
+++ b/configure.ac	2023-06-30 10:03:35.546892375 -0400
@@ -171,7 +171,7 @@
         AC_MSG_RESULT(yes)
         AC_DEFINE([HAVE_WEBP], [1], [Define to 1 if WEBP is around])
         TEMP_CPPFLAGS="$TEMP_CPPFLAGS "`pkgconf --cflags libwebpmux`
-        TEMP_LIBS="$TEMP_LIBS "`pkgconf --libs libwebpmux`
+        TEMP_LIBS="$TEMP_LIBS "`pkgconf --libs libwebpmux libwebp`
       ],[
         AC_MSG_RESULT(no)
       ]
```

### Relevant MotionPlus log output (at log_level 8)

```shell
N/A
```

**Comment by CRCinAU** [comment]
Can confirm that this patch fixes the build.

**Comment by gene-git** [comment]
Thanks for fixing.
